import numpy as np
from scipy import stats

data = np.array([1,2,2,3,4,4,4,5])
print('\n')
print('Массив data:')
print(data)
print('\n')
print('Массив data1:')
data1 = data.reshape(2,4)
print(data1)
print('\n')
print('Описательные статистики:')
print('\n')
print('Средние:')
sred = np.mean(data)
print('Среднее массива data:',sred)
sred1 = np.mean(data1)
print('Среднее массива data1:',sred1)
sred2 = np.mean(data1,axis = 1)
print('Среднее массива data1 по строкам:',sred2)
sred3 = np.mean(data1,axis = 0)
print('Среднее массива data1 по столбцам:',sred3)

print('\n')
print('Индексы:')
index_max = np.argmax(data)
print('Индекс MAX значения массива:', index_max)
print('MAX элемент массива data:',data[index_max])
index_min = np.argmin(data)
print('Индекс MIN значения массива:', index_min)
print('MIN элемент массива data:',data[index_min])

print('\n')
print('MAX и MIN:')
print('Максимальное значение массива data: ',np.max(data))
print('Минимальное значение массива data: ',np.min(data))
print('Максимальное значение массива data1: ',np.max(data1))
print('Минимальное значение массива data1: ',np.min(data1))
print('Максимальное значение строк массива data1: ',np.max(data1, axis = 1))
print('Максимальное значение столбцов массива data1: ',np.max(data1, axis = 0))

print('\n')
print('.prod - произведение эл.массива:')
print('Произведение всех эл. массива data: ',np.prod(data))
print('Произведение всех эл. массива data1: ',np.prod(data1))
print('Произведение всех эл. строк массива data1: ',np.prod(data1, axis = 1))
print('Произведение всех эл. столбцов массива data1: ',np.prod(data1, axis = 0))

print('\n')
print('.sum - произведение эл.массива:')
print('Сумма всех эл. массива data: ',np.sum(data))
print('Сумма всех эл. массива data1: ',np.sum(data1))
print('Сумма всех эл. строк массива data1: ',np.sum(data1, axis = 1))
print('Сумма всех эл. столбцов массива data1: ',np.sum(data1, axis = 0))


print('\n')
print('.var - дисперсия эл.массива:')
print('дисперсия всех эл. массива data: ',np.var(data))
print('дисперсия всех эл. массива data1: ',np.var(data1))
print('дисперсия всех эл. строк массива data1: ',np.var(data1, axis = 1))
print('дисперсия всех эл. столбцов массива data1: ',np.var(data1, axis = 0))

print('\n')
print('.std - ср.квадратическое откл. массива:')
print('ср.кв.откл. массива data: ',np.std(data))
print('ср.кв.откл.. массива data1: ',np.std(data1))
print('ср.кв.откл. строк массива data1: ',np.std(data1, axis = 1))
print('ср.кв.откл. столбцов массива data1: ',np.std(data1, axis = 0))


print('\n')
print('.median - медиана массива:')
print('медиана массива data: ',np.median(data))
print('медиана массива data1: ',np.median(data1))
print('медиана строк массива data1: ',np.median(data1, axis = 1))
print('медиана столбцов массива data1: ',np.median(data1, axis = 0))

print('\n')
print('.mod - мода массива:')
moda = stats.mode(data)
print('мода массива data: ',moda.mode)
print('счетчик ',moda.count)
moda1 = stats.mode(data1, axis = 1)
print('мода массива data1: ',moda1.mode)
print('счетчик ',moda1.count)

